// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubReq.proto

package com.itdotaer.dubbo.research.netty.protobuf;

public final class SubReqProto {
  private SubReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SubReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 orderId = 1;</code>
     */
    long getOrderId();

    /**
     * <code>string productName = 2;</code>
     */
    java.lang.String getProductName();
    /**
     * <code>string productName = 2;</code>
     */
    com.google.protobuf.ByteString
        getProductNameBytes();

    /**
     * <code>int64 price = 3;</code>
     */
    long getPrice();
  }
  /**
   * Protobuf type {@code SubReq}
   */
  public  static final class SubReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SubReq)
      SubReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubReq.newBuilder() to construct.
    private SubReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubReq() {
      orderId_ = 0L;
      productName_ = "";
      price_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              orderId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              productName_ = s;
              break;
            }
            case 24: {

              price_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.internal_static_SubReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.internal_static_SubReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq.class, com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq.Builder.class);
    }

    public static final int ORDERID_FIELD_NUMBER = 1;
    private long orderId_;
    /**
     * <code>int64 orderId = 1;</code>
     */
    public long getOrderId() {
      return orderId_;
    }

    public static final int PRODUCTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object productName_;
    /**
     * <code>string productName = 2;</code>
     */
    public java.lang.String getProductName() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productName_ = s;
        return s;
      }
    }
    /**
     * <code>string productName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 3;
    private long price_;
    /**
     * <code>int64 price = 3;</code>
     */
    public long getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (orderId_ != 0L) {
        output.writeInt64(1, orderId_);
      }
      if (!getProductNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productName_);
      }
      if (price_ != 0L) {
        output.writeInt64(3, price_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (orderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, orderId_);
      }
      if (!getProductNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productName_);
      }
      if (price_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq)) {
        return super.equals(obj);
      }
      com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq other = (com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq) obj;

      boolean result = true;
      result = result && (getOrderId()
          == other.getOrderId());
      result = result && getProductName()
          .equals(other.getProductName());
      result = result && (getPrice()
          == other.getPrice());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOrderId());
      hash = (37 * hash) + PRODUCTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getProductName().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPrice());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SubReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SubReq)
        com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.internal_static_SubReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.internal_static_SubReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq.class, com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq.Builder.class);
      }

      // Construct using com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        orderId_ = 0L;

        productName_ = "";

        price_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.internal_static_SubReq_descriptor;
      }

      @java.lang.Override
      public com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq getDefaultInstanceForType() {
        return com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq build() {
        com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq buildPartial() {
        com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq result = new com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq(this);
        result.orderId_ = orderId_;
        result.productName_ = productName_;
        result.price_ = price_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq) {
          return mergeFrom((com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq other) {
        if (other == com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq.getDefaultInstance()) return this;
        if (other.getOrderId() != 0L) {
          setOrderId(other.getOrderId());
        }
        if (!other.getProductName().isEmpty()) {
          productName_ = other.productName_;
          onChanged();
        }
        if (other.getPrice() != 0L) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long orderId_ ;
      /**
       * <code>int64 orderId = 1;</code>
       */
      public long getOrderId() {
        return orderId_;
      }
      /**
       * <code>int64 orderId = 1;</code>
       */
      public Builder setOrderId(long value) {
        
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 orderId = 1;</code>
       */
      public Builder clearOrderId() {
        
        orderId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object productName_ = "";
      /**
       * <code>string productName = 2;</code>
       */
      public java.lang.String getProductName() {
        java.lang.Object ref = productName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          productName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string productName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProductNameBytes() {
        java.lang.Object ref = productName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string productName = 2;</code>
       */
      public Builder setProductName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string productName = 2;</code>
       */
      public Builder clearProductName() {
        
        productName_ = getDefaultInstance().getProductName();
        onChanged();
        return this;
      }
      /**
       * <code>string productName = 2;</code>
       */
      public Builder setProductNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productName_ = value;
        onChanged();
        return this;
      }

      private long price_ ;
      /**
       * <code>int64 price = 3;</code>
       */
      public long getPrice() {
        return price_;
      }
      /**
       * <code>int64 price = 3;</code>
       */
      public Builder setPrice(long value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 price = 3;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SubReq)
    }

    // @@protoc_insertion_point(class_scope:SubReq)
    private static final com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq();
    }

    public static com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubReq>
        PARSER = new com.google.protobuf.AbstractParser<SubReq>() {
      @java.lang.Override
      public SubReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.itdotaer.dubbo.research.netty.protobuf.SubReqProto.SubReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014SubReq.proto\"=\n\006SubReq\022\017\n\007orderId\030\001 \001(" +
      "\003\022\023\n\013productName\030\002 \001(\t\022\r\n\005price\030\003 \001(\003B9\n" +
      "*com.itdotaer.dubbo.research.netty.proto" +
      "bufB\013SubReqProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SubReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SubReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubReq_descriptor,
        new java.lang.String[] { "OrderId", "ProductName", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
